# Generated by Django 3.2.4 on 2021-08-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Second_name', models.CharField(max_length=20)),
                ('Age', models.SmallIntegerField(blank=True, null=True)),
                ('Gender', models.CharField(choices=[('1', 'Female'), ('2', 'Male')], max_length=10)),
                ('Courses_trained', models.CharField(max_length=20)),
                ('Email_Adress', models.EmailField(blank=True, max_length=254, null=True)),
                ('Salary', models.PositiveBigIntegerField(blank=True, null=True)),
                ('Profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('Date_hired', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
