# Generated by Django 3.2.4 on 2021-08-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='Age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
