# Generated by Django 3.2.4 on 2021-08-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_trainer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='Date_hired',
        ),
    ]
