# Generated by Django 3.2.4 on 2021-08-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_remove_trainer_date_hired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='Courses_trained',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='Email_Adress',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='Salary',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='Second_name',
        ),
        migrations.AddField(
            model_name='trainer',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='courses_trained',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='email_Adress',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='fecond_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gender',
            field=models.CharField(choices=[('1', 'Female'), ('2', 'Male')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trainer',
            name='salary',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
