# Generated by Django 3.2.4 on 2021-08-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20210814_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='fecond_name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email_Adress',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
