# Generated by Django 3.2.4 on 2021-08-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20210817_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='email_Adress',
            new_name='email_address',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='gender',
        ),
    ]
