# Generated by Django 3.2.4 on 2021-08-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_alter_trainer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='courses_trained',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
