# Generated by Django 3.2.4 on 2021-10-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_trainer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='gender',
        ),
    ]
