# Generated by Django 3.2.4 on 2021-08-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12, null=True)),
                ('last_name', models.CharField(max_length=12, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('parent_name', models.CharField(max_length=12, null=True)),
                ('parent_phone_number', models.CharField(max_length=15, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('nationality', models.CharField(choices=[('1', 'Ugandan'), ('2', 'Kenyan'), ('3', 'Rwandan'), ('4', 'South Sudanese'), ('5', 'Sudanese')], max_length=15, null=True)),
                ('date_of_enrollment', models.DateField(null=True)),
                ('medical_report', models.FileField(blank=True, null=True, upload_to='')),
                ('email_address', models.EmailField(max_length=50, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('nationalId', models.CharField(max_length=12, null=True)),
                ('county_or_district', models.CharField(max_length=12, null=True)),
                ('language', models.CharField(choices=[('1', 'English'), ('2', 'French'), ('3', 'Kiswahili'), ('4', 'Kinyarwanda'), ('5', 'sudanese')], max_length=15, null=True)),
            ],
        ),
    ]
