# Generated by Django 3.2.4 on 2021-08-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210826_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile',
            new_name='photo',
        ),
    ]
