# Generated by Django 3.2.4 on 2021-08-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_profile_student_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo',
            new_name='profile',
        ),
    ]
