# Generated by Django 3.2.4 on 2021-09-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(default='SOME STRING', upload_to='docs/'),
        ),
    ]
