# Generated by Django 3.2.4 on 2021-08-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('guests', models.CharField(max_length=20, null=True)),
                ('event_task', models.CharField(max_length=20, null=True)),
                ('venue', models.CharField(max_length=20, null=True)),
                ('event_id', models.CharField(max_length=20, null=True)),
                ('duration', models.DurationField(null=True)),
            ],
        ),
    ]
