# Generated by Django 3.2.4 on 2021-08-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_rename_calender_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
