# Generated by Django 3.2.4 on 2021-08-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_auto_20210824_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
    ]
